### ISSUE TITLE
Error on Ubuntu: Win32Exception: Text file busy

### ISSUE THREAD

**Issue by bkoelman** [asimmon/ephemeral-mongo#91]
### Version

3.0.0

### Packages

EphemeralMongo

### Operating System

Ubuntu 24.04.2 LTS (GitHub Actions cloud-hosted runner)

### CPU architecture

Don't know, uses "ubuntu-latest" from https://github.com/actions/runner-images

### Context

GitHub Actions

### What happened?

I'm getting random failures on Ubuntu Linux in GitHub Actions when running tests. They all fail with the following message:

```
System.ComponentModel.Win32Exception : An error occurred trying to start process '/home/runner/.local/share/ephemeral-mongo/bin/mongod/mongod-targeted-8/8.0.8/mongod' with working directory '/home/runner/work/JsonApiDotNetCore.MongoDb/JsonApiDotNetCore.MongoDb/test/JsonApiDotNetCoreMongoDbTests/bin/Release/net8.0'. Text file busy
```

Sometimes, all 534 tests succeed, and sometimes, they all fail. I've seen the failure happen a few times on Ubuntu. I haven't encountered the problem on Windows or macOS in GitHub Actions. Running locally on Windows 11 always succeeds.

Fragment from the logs:

```
2025-04-27T00:26:52.7802343Z ##[error]System.ComponentModel.Win32Exception : An error occurred trying to start process '/home/runner/.local/share/ephemeral-mongo/bin/mongod/mongod-targeted-8/8.0.8/mongod' with working directory '/home/runner/work/JsonApiDotNetCore.MongoDb/JsonApiDotNetCore.MongoDb/test/JsonApiDotNetCoreMongoDbTests/bin/Release/net8.0'. Text file busy
2025-04-27T00:26:52.7816874Z 
2025-04-27T00:26:52.7818497Z   Failed JsonApiDotNetCoreMongoDbTests.IntegrationTests.QueryStrings.Filtering.FilterOperatorTests.Can_filter_comparison_on_TimeSpan(matchingValue: "2:15:28:54.997", nonMatchingValue: "2:16:22:41.736", filterOperator: LessThan, filterValue: "2:16:22:41.736") [9 s]
2025-04-27T00:26:52.7820317Z   Error Message:
2025-04-27T00:26:52.7822494Z    System.ComponentModel.Win32Exception : An error occurred trying to start process '/home/runner/.local/share/ephemeral-mongo/bin/mongod/mongod-targeted-8/8.0.8/mongod' with working directory '/home/runner/work/JsonApiDotNetCore.MongoDb/JsonApiDotNetCore.MongoDb/test/JsonApiDotNetCoreMongoDbTests/bin/Release/net8.0'. Text file busy
2025-04-27T00:26:52.7825108Z   Stack Trace:
2025-04-27T00:26:52.7826964Z      at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
2025-04-27T00:26:52.7829153Z    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
2025-04-27T00:26:52.7830573Z    at EphemeralMongo.MongodProcess.StartAndWaitForConnectionReadinessAsync(CancellationToken cancellationToken) in /_/src/EphemeralMongo/MongodProcess.cs:line 60
2025-04-27T00:26:52.7832364Z    at EphemeralMongo.MongodProcess.StartAsync(CancellationToken cancellationToken) in /_/src/EphemeralMongo/MongodProcess.cs:line 21
2025-04-27T00:26:52.7834108Z    at EphemeralMongo.MongoRunner.RunInternalAsync(CancellationToken cancellationToken) in /_/src/EphemeralMongo/MongoRunner.cs:line 114
2025-04-27T00:26:52.7835688Z    at EphemeralMongo.MongoRunner.Run(MongoRunnerOptions options, CancellationToken cancellationToken) in /_/src/EphemeralMongo/MongoRunner.cs:line 42
2025-04-27T00:26:52.7837066Z    at TestBuildingBlocks.MongoRunnerProvider.Get() in /_/test/TestBuildingBlocks/MongoRunnerProvider.cs:line 42
2025-04-27T00:26:52.7838378Z    at TestBuildingBlocks.IntegrationTestContext`2.StartMongoDb() in /_/test/TestBuildingBlocks/IntegrationTestContext.cs:line 61
2025-04-27T00:26:52.7839305Z    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2025-04-27T00:26:52.7840164Z    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2025-04-27T00:26:52.7840981Z    at System.Lazy`1.CreateValue()
2025-04-27T00:26:52.7842051Z    at TestBuildingBlocks.IntegrationTestContext`2.<CreateFactory>b__14_1(IServiceProvider _) in /_/test/TestBuildingBlocks/IntegrationTestContext.cs:line 97
2025-04-27T00:26:52.7844036Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2025-04-27T00:26:52.7846068Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2025-04-27T00:26:52.7848376Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2025-04-27T00:26:52.7850482Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2025-04-27T00:26:52.7852655Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2025-04-27T00:26:52.7855400Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2025-04-27T00:26:52.7858029Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
2025-04-27T00:26:52.7860194Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2025-04-27T00:26:52.7862025Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2025-04-27T00:26:52.7864357Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
2025-04-27T00:26:52.7866418Z    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
2025-04-27T00:26:52.7868255Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
2025-04-27T00:26:52.7870006Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2025-04-27T00:26:52.7871821Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2025-04-27T00:26:52.7873839Z    at TestBuildingBlocks.IntegrationTestContext`2.RunOnDatabaseAsync(Func`2 asyncAction) in /_/test/TestBuildingBlocks/IntegrationTestContext.cs:line 141
2025-04-27T00:26:52.7875684Z    at TestBuildingBlocks.IntegrationTestContext`2.RunOnDatabaseAsync(Func`2 asyncAction) in /_/test/TestBuildingBlocks/IntegrationTestContext.cs:line 143
2025-04-27T00:26:52.7878928Z    at JsonApiDotNetCoreMongoDbTests.IntegrationTests.QueryStrings.Filtering.FilterOperatorTests.Can_filter_comparison_on_TimeSpan(String matchingValue, String nonMatchingValue, ComparisonOperator filterOperator, String filterValue) in /_/test/JsonApiDotNetCoreMongoDbTests/IntegrationTests/QueryStrings/Filtering/FilterOperatorTests.cs:line 320
2025-04-27T00:26:52.7881579Z --- End of stack trace from previous location ---
2025-04-27T00:26:52.7881932Z 
```

Full log at: https://github.com/json-api-dotnet/JsonApiDotNetCore.MongoDb/actions/runs/14686500320/job/41215789281?pr=95

A quick Google search on the error message [tells me](https://stackoverflow.com/questions/16764946/what-generates-the-text-file-busy-message-in-unix) this is caused by trying to modify an executable while it is executing.

Any idea what could be going on here?

**Comment by bkoelman** [comment]
Perhaps because our tests run against multiple target frameworks (net8.0/9.0) in parallel? The path doesn't seem to include the target framework. Our static lock to initialize isn't OS-wide.

Interestingly, I don't think I've ever seen this error with the 2.x versions.

**Comment by asimmon** [comment]
This couldn't happen with the 2.x versions as the MongoDB binaries were copied from the NuGet package at build time. Now, we're downloading them at runtime.

I encountered this bug in Ubuntu CI runs several times in the past weeks. I also think multi-targeting is the root cause. I ended up writing some basic retry logic in #89. This was living on the main branch only. I was planning to release later, but since you're encountering this issue too, you could help me check if the workaround works well in this [preview version of 3.1.0](https://www.nuget.org/packages/EphemeralMongo/3.1.0-preview.1). On my side, the Ubuntu CI has been green ever since.

Full release notes: https://github.com/asimmon/ephemeral-mongo/releases/tag/3.1.0-preview.1

**Comment by asimmon** [comment]
I just released 3.1.0 (stable), as I'm no longer experiencing this behavior.

**Comment by bkoelman** [comment]
Thanks for the new version. I hadn't had a chance to try it yet. I'll report back when the error remains with v3.1.
